"""
Airline Passenger Satisfaction Analysis — Interactive UI Module

Loads trained models from models/ (generated by the last cell of projecttwin.ipynb).
Falls back to hardcoded logistic-regression coefficients when the pickle files are absent.
"""

import os
import pickle
import streamlit as st
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# ─────────────────────────────────────────────────────────────
# PAGE CONFIG
# ─────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Airline Satisfaction Analyzer",
    page_icon="✈️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─────────────────────────────────────────────────────────────
# CUSTOM CSS
# ─────────────────────────────────────────────────────────────
st.markdown("""
<style>
    [data-testid="stAppViewContainer"] {background: #0f172a;}
    [data-testid="stSidebar"] {background: #1e293b;}
    h1, h2, h3, h4 {color: #f1f5f9;}
    p, li, label, .stMarkdown {color: #cbd5e1;}

    .metric-card {
        background: linear-gradient(135deg, #1e293b, #0f172a);
        border: 1px solid #334155; border-radius: 14px;
        padding: 18px 22px; text-align: center; transition: transform .15s;
    }
    .metric-card:hover {transform: translateY(-3px);}
    .metric-value {font-size: 2.1rem; font-weight: 700; color: #38bdf8;}
    .metric-label {font-size: .85rem; color: #94a3b8; margin-top: 4px;}

    .pred-satisfied {
        background: linear-gradient(135deg, #052e16, #14532d);
        border: 2px solid #22c55e; border-radius: 14px;
        padding: 20px 28px; text-align: center;
        font-size: 1.4rem; font-weight: 700; color: #4ade80;
    }
    .pred-dissatisfied {
        background: linear-gradient(135deg, #2d1017, #450a0a);
        border: 2px solid #ef4444; border-radius: 14px;
        padding: 20px 28px; text-align: center;
        font-size: 1.4rem; font-weight: 700; color: #f87171;
    }

    .section-header {
        border-left: 4px solid #38bdf8; padding-left: 12px;
        margin: 10px 0 18px 0; font-size: 1.25rem;
        font-weight: 600; color: #e2e8f0;
    }
    [data-testid="stSidebarNav"] {display: none;}
    .sidebar-title {font-size: 1.1rem; font-weight: 700; color: #38bdf8; margin-bottom: 4px;}

    .stButton > button {
        background: linear-gradient(135deg, #0ea5e9, #6366f1);
        color: white; border: none; border-radius: 10px;
        font-weight: 600; padding: 10px 28px; transition: opacity .15s;
    }
    .stButton > button:hover {opacity: .88;}

    .stTabs [data-baseweb="tab-list"] {background: #1e293b; border-radius: 10px;}
    .stTabs [data-baseweb="tab"] {color: #94a3b8;}
    .stTabs [aria-selected="true"] {color: #38bdf8; border-bottom-color: #38bdf8;}
    .stDataFrame {border-radius: 10px; overflow: hidden;}
</style>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────
# MODEL LOADING
# ─────────────────────────────────────────────────────────────

MODELS_DIR = os.path.join(os.path.dirname(__file__), "models")

@st.cache_resource
def load_models():
    """Load pickled models from models/.  Returns None for each missing file."""
    def _load(name):
        path = os.path.join(MODELS_DIR, name)
        if os.path.exists(path):
            with open(path, "rb") as f:
                return pickle.load(f)
        return None

    return {
        "lda":            _load("lda.pkl"),
        "qda":            _load("qda.pkl"),
        "gnb":            _load("gnb.pkl"),
        "lr_bin":         _load("lr_bin.pkl"),
        "scaler":         _load("scaler.pkl"),
        "le":             _load("le.pkl"),
        "bin_raw_cols":   _load("bin_raw_cols.pkl"),
        "bin_final_cols": _load("bin_final_cols.pkl"),
        "multi_log_reg":  _load("multi_log_reg.pkl"),
        "scaler_multi":   _load("scaler_multi.pkl"),
        "multi_raw_cols": _load("multi_raw_cols.pkl"),
    }

MODELS = load_models()
MODELS_LOADED = all(
    MODELS[k] is not None
    for k in ("lda", "qda", "gnb", "lr_bin", "scaler", "bin_raw_cols", "bin_final_cols")
)


# ─────────────────────────────────────────────────────────────
# FEATURE CONSTRUCTION & REAL INFERENCE
# ─────────────────────────────────────────────────────────────

# Expected raw feature order (must match X_tr.columns from the notebook)
_BIN_RAW_COLS = [
    "Gender_Male", "Customer Type_disloyal Customer", "Age",
    "Type of Travel_Personal Travel", "Class_Eco", "Class_Eco Plus",
    "Flight Distance",
    "Inflight wifi service", "Departure/Arrival time convenient",
    "Ease of Online booking", "Gate location", "Food and drink",
    "Online boarding", "Seat comfort", "Inflight entertainment",
    "On-board service", "Leg room service", "Baggage handling",
    "Checkin service", "Inflight service", "Cleanliness",
    "Departure Delay in Minutes", "Arrival Delay in Minutes",
]


def build_feature_vector(row_dict: dict) -> pd.DataFrame:
    """
    Build the exact feature vector the binary classifiers expect:
      1. Align raw features to X_tr column order
      2. StandardScaler.transform()
      3. Insert 'const' = 1.0 at position 0  (sm.add_constant was applied in notebook)
      4. Drop 'Departure Delay in Minutes'    (removed as confounding variable)
    """
    raw_cols = MODELS["bin_raw_cols"] if MODELS_LOADED else _BIN_RAW_COLS
    df_raw = pd.DataFrame([row_dict])[raw_cols]
    df_scaled = pd.DataFrame(
        MODELS["scaler"].transform(df_raw), columns=raw_cols
    )
    df_scaled.insert(0, "const", 1.0)
    df_scaled = df_scaled.drop("Departure Delay in Minutes", axis=1)
    return df_scaled


def real_predict(model, feature_df: pd.DataFrame):
    """Returns (label_str, probability_of_satisfied)."""
    prob = model.predict_proba(feature_df)[0, 1]
    # le encodes: 0=neutral/dissatisfied, 1=satisfied (alphabetical order)
    label = "satisfied" if prob >= 0.5 else "neutral or dissatisfied"
    return label, float(prob)


# ─────────────────────────────────────────────────────────────
# FALLBACK INFERENCE  (hardcoded coefficients when no pickles)
# ─────────────────────────────────────────────────────────────

_FB_INTERCEPT = -0.10
_FB_COEF = {
    "wifi": 0.24, "online_boarding": 0.40, "seat_comfort": 0.27,
    "inflight_entertainment": 0.30, "food_drink": 0.10,
    "onboard_service": 0.20, "cleanliness": 0.14,
    "arrival_delay_norm": -0.12, "personal_travel": -1.20,
    "disloyal": -0.75, "age_norm": 0.03, "distance_norm": 0.04,
}


def fallback_predict(inputs: dict) -> tuple[str, float]:
    score = _FB_INTERCEPT + sum(_FB_COEF.get(k, 0) * v for k, v in inputs.items())
    prob = float(1 / (1 + np.exp(-score)))
    label = "satisfied" if prob >= 0.5 else "neutral or dissatisfied"
    return label, prob


# ─────────────────────────────────────────────────────────────
# HARDCODED DISPLAY DATA  (metrics / examples – from notebook outputs)
# ─────────────────────────────────────────────────────────────

MODEL_METRICS = {
    "LDA (optimal threshold)": {
        "accuracy": 0.87, "precision_0": 0.87, "recall_0": 0.91,
        "f1_0": 0.89, "precision_1": 0.87, "recall_1": 0.82,
        "f1_1": 0.85, "macro_f1": 0.87, "roc_auc": 0.944,
        "color": "#38bdf8",
    },
    "LDA (default threshold)": {
        "accuracy": 0.87, "precision_0": 0.87, "recall_0": 0.90,
        "f1_0": 0.88, "precision_1": 0.86, "recall_1": 0.83,
        "f1_1": 0.85, "macro_f1": 0.87, "roc_auc": 0.944,
        "color": "#818cf8",
    },
    "Gaussian Naive Bayes": {
        "accuracy": 0.86, "precision_0": 0.86, "recall_0": 0.90,
        "f1_0": 0.88, "precision_1": 0.86, "recall_1": 0.81,
        "f1_1": 0.83, "macro_f1": 0.86, "roc_auc": 0.932,
        "color": "#34d399",
    },
    "QDA": {
        "accuracy": 0.85, "precision_0": 0.85, "recall_0": 0.89,
        "f1_0": 0.87, "precision_1": 0.85, "recall_1": 0.80,
        "f1_1": 0.83, "macro_f1": 0.85, "roc_auc": 0.921,
        "color": "#fb923c",
    },
    "Logistic Regression (Binary)": {
        "accuracy": 0.87, "precision_0": 0.87, "recall_0": 0.90,
        "f1_0": 0.88, "precision_1": 0.86, "recall_1": 0.83,
        "f1_1": 0.84, "macro_f1": 0.86, "roc_auc": 0.940,
        "color": "#f472b6",
    },
}

MULTINOMIAL_REPORT = {
    "Class": ["Business", "Eco", "Eco Plus", "Macro Avg", "Weighted Avg"],
    "Precision": [0.88, 0.78, 0.17, 0.61, 0.78],
    "Recall":    [0.79, 0.73, 0.35, 0.62, 0.73],
    "F1-score":  [0.83, 0.75, 0.23, 0.60, 0.75],
    "Support":   [12495, 11564, 1917, 25976, 25976],
}

REGRESSION_RESULTS = {
    "Model": ["Linear Regression (OLS)", "Poisson Regression (GLM)"],
    "RMSE (minutes)": [11.02, 55.44],
    "Notes": [
        "Lower test RMSE; can produce a few negative predicted delays",
        "Guarantees non-negative predictions; higher RMSE on this target",
    ],
}

TOP_FEATURES = [
    ("Online boarding", 0.826),
    ("Type of Travel: Personal", -1.258),
    ("Customer Type: Disloyal", -0.786),
    ("Inflight entertainment", 0.621),
    ("Seat comfort", 0.558),
    ("Arrival Delay (min)", -0.341),
    ("Inflight wifi service", 0.487),
    ("On-board service", 0.412),
    ("Leg room service", 0.378),
    ("Cleanliness", 0.294),
]

EXAMPLE_PASSENGERS = [
    {
        "label": "Business Traveller — Loyal, High Ratings",
        "gender": "Male", "customer_type": "Loyal Customer",
        "age": 42, "travel_type": "Business travel", "flight_class": "Business",
        "flight_distance": 850,
        "wifi": 4, "time_conv": 4, "online_book": 4, "gate": 3,
        "food": 4, "boarding": 5, "seat": 4, "entertainment": 5,
        "onboard": 4, "legroom": 4, "baggage": 4, "checkin": 4,
        "inflight_svc": 5, "clean": 5,
        "dep_delay": 0, "arr_delay": 0,
        "expected": "satisfied", "probability": 0.92,
    },
    {
        "label": "Personal Traveller — Disloyal, Low Ratings",
        "gender": "Female", "customer_type": "disloyal Customer",
        "age": 22, "travel_type": "Personal Travel", "flight_class": "Eco",
        "flight_distance": 320,
        "wifi": 2, "time_conv": 2, "online_book": 2, "gate": 2,
        "food": 2, "boarding": 2, "seat": 2, "entertainment": 1,
        "onboard": 2, "legroom": 2, "baggage": 2, "checkin": 2,
        "inflight_svc": 2, "clean": 2,
        "dep_delay": 45, "arr_delay": 52,
        "expected": "neutral or dissatisfied", "probability": 0.01,
    },
    {
        "label": "Business Traveller — Eco Plus, Mixed Ratings",
        "gender": "Female", "customer_type": "Loyal Customer",
        "age": 35, "travel_type": "Business travel", "flight_class": "Eco Plus",
        "flight_distance": 620,
        "wifi": 3, "time_conv": 3, "online_book": 3, "gate": 3,
        "food": 3, "boarding": 3, "seat": 3, "entertainment": 3,
        "onboard": 3, "legroom": 3, "baggage": 3, "checkin": 3,
        "inflight_svc": 3, "clean": 3,
        "dep_delay": 10, "arr_delay": 8,
        "expected": "neutral or dissatisfied", "probability": 0.44,
    },
]

# Map from display model name → MODELS key
_SKLEARN_MODELS = {
    "LDA":                  "lda",
    "QDA":                  "qda",
    "Gaussian Naive Bayes": "gnb",
    "Logistic Regression":  "lr_bin",
}


# ─────────────────────────────────────────────────────────────
# SIDEBAR
# ─────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown('<p class="sidebar-title">✈️ Satisfaction Analyzer</p>', unsafe_allow_html=True)
    st.markdown("*Airline Passenger Satisfaction · ML Study*")
    st.divider()
    page = st.radio(
        "Navigate",
        ["🏠 Overview", "🔮 Live Predictor", "📊 Model Comparison", "📋 Example Results"],
        label_visibility="collapsed",
    )
    st.divider()
    st.markdown("**Dataset**")
    st.markdown("- 103,904 training samples\n- 25,976 test samples\n- 23 features")
    st.markdown("**Best Model**")
    st.markdown("- LDA · Accuracy **87%** · AUC **0.944**")
    st.divider()
    if MODELS_LOADED:
        st.success("✅ Trained models loaded")
    else:
        st.warning("⚠️ models/ not found\nUsing fallback coefficients\n\nRun the last cell of `projecttwin.ipynb` to generate pickle files.")


# ─────────────────────────────────────────────────────────────
# PAGE 1 — OVERVIEW
# ─────────────────────────────────────────────────────────────
if page == "🏠 Overview":
    st.markdown("## ✈️ Airline Passenger Satisfaction Analysis")
    st.markdown("End-to-end ML study: **EDA → Binary & Multinomial Logistic Regression → LDA / QDA → Naïve Bayes → Regression Models**")
    st.divider()

    c1, c2, c3, c4, c5 = st.columns(5)
    kpis = [
        ("129,880", "Total Passengers"),
        ("23", "Features"),
        ("87%", "Best Accuracy"),
        ("0.944", "Best ROC-AUC"),
        ("5", "Models Trained"),
    ]
    for col, (val, lbl) in zip([c1, c2, c3, c4, c5], kpis):
        col.markdown(
            f'<div class="metric-card"><div class="metric-value">{val}</div>'
            f'<div class="metric-label">{lbl}</div></div>',
            unsafe_allow_html=True,
        )

    st.markdown("<br>", unsafe_allow_html=True)
    col_left, col_right = st.columns(2)

    with col_left:
        st.markdown('<div class="section-header">Tasks Addressed</div>', unsafe_allow_html=True)
        for title, desc in {
            "🎯 Binary Classification": "Predict overall passenger satisfaction\n(satisfied vs neutral/dissatisfied)",
            "📦 Multinomial Classification": "Predict travel class\n(Business · Eco · Eco Plus)",
            "📏 Regression": "Predict arrival delay (minutes)\n(Linear OLS vs Poisson GLM)",
        }.items():
            with st.expander(title, expanded=True):
                st.markdown(desc)

    with col_right:
        st.markdown('<div class="section-header">Pipeline</div>', unsafe_allow_html=True)
        for num, title, desc in [
            ("1", "Data Loading & EDA", "Explore distributions, class balance, correlations"),
            ("2", "Preprocessing", "Median imputation, one-hot encoding, StandardScaler"),
            ("3", "Binary Classification", "Logistic Regression · LDA · QDA · Naive Bayes"),
            ("4", "Multinomial Classification", "Logistic Regression (3 classes)"),
            ("5", "Regression", "OLS Linear · Poisson GLM for arrival delay (minutes)"),
            ("6", "Model Evaluation", "Accuracy · Precision · Recall · F1 · ROC-AUC"),
        ]:
            st.markdown(
                f"<div style='display:flex;align-items:flex-start;gap:12px;margin-bottom:10px;'>"
                f"<div style='background:#0ea5e9;color:white;border-radius:50%;width:28px;height:28px;"
                f"display:flex;align-items:center;justify-content:center;font-weight:700;flex-shrink:0'>{num}</div>"
                f"<div><b style='color:#e2e8f0'>{title}</b><br>"
                f"<span style='color:#94a3b8;font-size:.85rem'>{desc}</span></div></div>",
                unsafe_allow_html=True,
            )

    st.divider()
    st.markdown('<div class="section-header">Key Findings</div>', unsafe_allow_html=True)
    for col, (title, body) in zip(st.columns(3), [
        ("🏆 Top Predictor", "Online boarding (coef +0.826) is the strongest positive driver of satisfaction."),
        ("✈️ Travel Type Matters", "Personal travellers are far less likely to be satisfied (coef −1.258 vs business travel)."),
        ("⏱️ Delays Hurt", "Each 10-min increase in arrival delay reduces satisfaction log-odds by ~0.12."),
    ]):
        col.markdown(
            f"<div class='metric-card' style='text-align:left'>"
            f"<div style='font-size:1rem;font-weight:700;color:#e2e8f0;margin-bottom:6px'>{title}</div>"
            f"<div style='color:#94a3b8;font-size:.88rem'>{body}</div></div>",
            unsafe_allow_html=True,
        )

    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown('<div class="section-header">Class Distribution (Training Set)</div>', unsafe_allow_html=True)
    values = [56428, 47476]
    fig_dist = go.Figure(go.Bar(
        x=["Satisfied", "Neutral/Dissatisfied"],
        y=values, marker_color=["#22c55e", "#ef4444"],
        text=[f"{v:,}<br>({v/sum(values)*100:.1f}%)" for v in values],
        textposition="outside", textfont=dict(color="#e2e8f0"),
    ))
    fig_dist.update_layout(
        plot_bgcolor="#1e293b", paper_bgcolor="#0f172a",
        font=dict(color="#e2e8f0"), height=300,
        margin=dict(t=30, b=20, l=20, r=20),
        yaxis=dict(gridcolor="#334155", color="#94a3b8"),
        xaxis=dict(color="#94a3b8"), showlegend=False,
    )
    st.plotly_chart(fig_dist, use_container_width=True)


# ─────────────────────────────────────────────────────────────
# PAGE 2 — LIVE PREDICTOR
# ─────────────────────────────────────────────────────────────
elif page == "🔮 Live Predictor":
    st.markdown("## 🔮 Live Passenger Satisfaction Predictor")

    mode_badge = (
        "🟢 **Using trained sklearn models** loaded from `models/`"
        if MODELS_LOADED else
        "🟡 **Fallback mode** — run the last notebook cell to generate `models/` for real predictions"
    )
    st.info(mode_badge)
    st.divider()

    with st.form("predictor_form"):
        c1, c2, c3, c4 = st.columns(4)

        with c1:
            st.markdown("**Passenger Profile**")
            gender        = st.selectbox("Gender", ["Male", "Female"])
            age           = st.slider("Age", 7, 85, 35)
            customer_type = st.selectbox("Customer Type", ["Loyal Customer", "disloyal Customer"])
            if MODELS_LOADED:
                model_choice = st.selectbox("Model", list(_SKLEARN_MODELS.keys()))
            else:
                model_choice = None

        with c2:
            st.markdown("**Flight Details**")
            travel_type     = st.selectbox("Type of Travel", ["Business travel", "Personal Travel"])
            flight_class    = st.selectbox("Class", ["Business", "Eco Plus", "Eco"])
            flight_distance = st.number_input("Flight Distance (miles)", 50, 5000, 800, step=50)
            arr_delay       = st.number_input("Arrival Delay (min)", 0, 500, 0)

        with c3:
            st.markdown("**Service Ratings — Part 1 (1–5)**")
            wifi          = st.slider("Inflight Wifi Service", 1, 5, 3)
            time_conv     = st.slider("Flight time convenience (1–5)", 1, 5, 3, help="How convenient were the scheduled departure and arrival times?")
            online_book   = st.slider("Ease of Online Booking", 1, 5, 3)
            gate          = st.slider("Gate Location", 1, 5, 3)
            food          = st.slider("Food & Drink", 1, 5, 3)
            boarding      = st.slider("Online Boarding", 1, 5, 3)
            seat          = st.slider("Seat Comfort", 1, 5, 3)

        with c4:
            st.markdown("**Service Ratings — Part 2 (1–5)**")
            entertainment = st.slider("Inflight Entertainment", 1, 5, 3)
            onboard       = st.slider("On-board Service", 1, 5, 3)
            legroom       = st.slider("Leg Room Service", 1, 5, 3)
            baggage       = st.slider("Baggage Handling", 1, 5, 3)
            checkin       = st.slider("Checkin Service", 1, 5, 3)
            inflight_svc  = st.slider("Inflight Service", 1, 5, 3)
            cleanliness   = st.slider("Cleanliness", 1, 5, 3)

        submitted = st.form_submit_button("🔮 Predict Satisfaction", use_container_width=True)

    if submitted:
        if MODELS_LOADED:
            row = {
                "Gender_Male":                         1 if gender == "Male" else 0,
                "Customer Type_disloyal Customer":     1 if customer_type == "disloyal Customer" else 0,
                "Age":                                 age,
                "Type of Travel_Personal Travel":      1 if travel_type == "Personal Travel" else 0,
                "Class_Eco":                           1 if flight_class == "Eco" else 0,
                "Class_Eco Plus":                      1 if flight_class == "Eco Plus" else 0,
                "Flight Distance":                     flight_distance,
                "Inflight wifi service":               wifi,
                "Departure/Arrival time convenient":   time_conv,
                "Ease of Online booking":              online_book,
                "Gate location":                       gate,
                "Food and drink":                      food,
                "Online boarding":                     boarding,
                "Seat comfort":                        seat,
                "Inflight entertainment":              entertainment,
                "On-board service":                    onboard,
                "Leg room service":                    legroom,
                "Baggage handling":                    baggage,
                "Checkin service":                     checkin,
                "Inflight service":                    inflight_svc,
                "Cleanliness":                         cleanliness,
                "Departure Delay in Minutes":          0,
                "Arrival Delay in Minutes":            arr_delay,
            }
            feat_df = build_feature_vector(row)
            model_obj = MODELS[_SKLEARN_MODELS[model_choice]]
            label, prob = real_predict(model_obj, feat_df)
        else:
            fb_inputs = {
                "wifi":                 wifi - 3,
                "online_boarding":      boarding - 3,
                "seat_comfort":         seat - 3,
                "inflight_entertainment": entertainment - 3,
                "food_drink":           food - 3,
                "onboard_service":      onboard - 3,
                "cleanliness":          cleanliness - 3,
                "arrival_delay_norm":   arr_delay / 10.0,
                "personal_travel":      1.0 if travel_type == "Personal Travel" else 0.0,
                "disloyal":             1.0 if customer_type == "disloyal Customer" else 0.0,
                "age_norm":             (age - 39) / 15.0,
                "distance_norm":        (flight_distance - 1190) / 800.0,
            }
            label, prob = fallback_predict(fb_inputs)

        st.markdown("<br>", unsafe_allow_html=True)
        css_class = "pred-satisfied" if label == "satisfied" else "pred-dissatisfied"
        icon = "✅" if label == "satisfied" else "❌"
        model_label = model_choice if MODELS_LOADED else "Logistic Regression (fallback)"
        st.markdown(
            f'<div class="{css_class}">{icon} Prediction: <span style="text-transform:uppercase">{label}</span>'
            f'<br><span style="font-size:1rem;font-weight:400">Satisfaction Probability: {prob:.1%}'
            f' &nbsp;·&nbsp; Model: {model_label}</span></div>',
            unsafe_allow_html=True,
        )

        st.markdown("<br>", unsafe_allow_html=True)
        col_gauge, col_factors = st.columns([1, 2])

        with col_gauge:
            fig_gauge = go.Figure(go.Indicator(
                mode="gauge+number",
                value=prob * 100,
                number={"suffix": "%", "font": {"color": "#38bdf8", "size": 40}},
                gauge={
                    "axis": {"range": [0, 100], "tickcolor": "#94a3b8"},
                    "bar": {"color": "#22c55e" if prob >= 0.5 else "#ef4444"},
                    "bgcolor": "#1e293b", "bordercolor": "#334155",
                    "steps": [
                        {"range": [0, 50],  "color": "#2d1017"},
                        {"range": [50, 100], "color": "#052e16"},
                    ],
                    "threshold": {"line": {"color": "white", "width": 3}, "value": 50},
                },
                title={"text": "Satisfaction Probability", "font": {"color": "#e2e8f0"}},
            ))
            fig_gauge.update_layout(
                paper_bgcolor="#0f172a", height=280,
                margin=dict(t=40, b=10, l=20, r=20),
            )
            st.plotly_chart(fig_gauge, use_container_width=True)

        with col_factors:
            st.markdown("**Service Rating Contributions** *(deviation from neutral rating of 3)*")
            svc_names = [
                "Online Boarding", "Inflight Entertainment", "Seat Comfort",
                "Inflight Wifi", "On-board Service", "Cleanliness",
                "Food & Drink", "Leg Room", "Baggage Handling",
                "Checkin Service", "Inflight Service",
            ]
            svc_vals = [
                _FB_COEF["online_boarding"]       * (boarding - 3),
                _FB_COEF["inflight_entertainment"] * (entertainment - 3),
                _FB_COEF["seat_comfort"]           * (seat - 3),
                _FB_COEF["wifi"]                   * (wifi - 3),
                _FB_COEF["onboard_service"]        * (onboard - 3),
                _FB_COEF["cleanliness"]            * (cleanliness - 3),
                _FB_COEF["food_drink"]             * (food - 3),
                0.18 * (legroom - 3),
                0.12 * (baggage - 3),
                0.14 * (checkin - 3),
                0.16 * (inflight_svc - 3),
            ]
            extra_names, extra_vals = [], []
            if travel_type == "Personal Travel":
                extra_names.append("Personal Travel"); extra_vals.append(_FB_COEF["personal_travel"])
            if customer_type == "disloyal Customer":
                extra_names.append("Disloyal Customer"); extra_vals.append(_FB_COEF["disloyal"])
            if arr_delay > 0:
                extra_names.append("Arrival Delay"); extra_vals.append(_FB_COEF["arrival_delay_norm"] * arr_delay / 10.0)

            all_names = svc_names + extra_names
            all_vals  = svc_vals  + extra_vals

            fig_factors = go.Figure(go.Bar(
                x=all_vals, y=all_names, orientation="h",
                marker_color=["#22c55e" if v > 0 else "#ef4444" for v in all_vals],
                text=[f"{v:+.2f}" for v in all_vals],
                textposition="outside", textfont=dict(color="#e2e8f0"),
            ))
            fig_factors.update_layout(
                plot_bgcolor="#1e293b", paper_bgcolor="#0f172a",
                font=dict(color="#e2e8f0"), height=360,
                margin=dict(t=10, b=10, l=10, r=60),
                xaxis=dict(gridcolor="#334155", color="#94a3b8", zeroline=True, zerolinecolor="#475569"),
                yaxis=dict(color="#94a3b8"),
            )
            st.plotly_chart(fig_factors, use_container_width=True)


# ─────────────────────────────────────────────────────────────
# PAGE 3 — MODEL COMPARISON
# ─────────────────────────────────────────────────────────────
elif page == "📊 Model Comparison":
    st.markdown("## 📊 Model Comparison Dashboard")
    st.markdown("Performance of all five binary classification models on the held-out test set (n = 25,976).")
    st.divider()

    tabs = st.tabs(["Binary Classification", "Multinomial Classification", "Regression Models"])

    with tabs[0]:
        model_names = list(MODEL_METRICS.keys())
        accs = [MODEL_METRICS[m]["accuracy"] for m in model_names]
        aucs = [MODEL_METRICS[m]["roc_auc"]   for m in model_names]
        f1s  = [MODEL_METRICS[m]["macro_f1"]  for m in model_names]
        cols = [MODEL_METRICS[m]["color"]     for m in model_names]

        fig_cmp = make_subplots(rows=1, cols=3, subplot_titles=["Accuracy", "ROC-AUC", "Macro F1"])
        for i, vals in enumerate([accs, aucs, f1s], 1):
            fig_cmp.add_trace(
                go.Bar(x=model_names, y=vals, marker_color=cols,
                       text=[f"{v:.3f}" for v in vals], textposition="outside",
                       textfont=dict(color="#e2e8f0"), showlegend=False),
                row=1, col=i,
            )
        fig_cmp.update_layout(
            plot_bgcolor="#1e293b", paper_bgcolor="#0f172a",
            font=dict(color="#e2e8f0"), height=420,
            margin=dict(t=50, b=80, l=20, r=20),
        )
        for ax in ["xaxis", "xaxis2", "xaxis3"]:
            fig_cmp.update_layout(**{ax: dict(tickangle=-25, color="#94a3b8")})
        for ax in ["yaxis", "yaxis2", "yaxis3"]:
            fig_cmp.update_layout(**{ax: dict(gridcolor="#334155", color="#94a3b8", range=[0.7, 1.0])})
        for ann in fig_cmp.layout.annotations:
            ann.font.color = "#e2e8f0"
        st.plotly_chart(fig_cmp, use_container_width=True)

        st.markdown('<div class="section-header">Detailed Classification Reports</div>', unsafe_allow_html=True)
        selected = st.selectbox("Select model", model_names)
        m = MODEL_METRICS[selected]
        df_report = pd.DataFrame({
            "Class": ["Neutral/Dissatisfied (0)", "Satisfied (1)", "Macro Avg"],
            "Precision": [m["precision_0"], m["precision_1"], (m["precision_0"]+m["precision_1"])/2],
            "Recall":    [m["recall_0"],    m["recall_1"],    (m["recall_0"]+m["recall_1"])/2],
            "F1-score":  [m["f1_0"],        m["f1_1"],        m["macro_f1"]],
        })
        st.dataframe(
            df_report.style.format({c: "{:.3f}" for c in ["Precision","Recall","F1-score"]})
                           .set_properties(**{"background-color":"#1e293b","color":"#e2e8f0"})
                           .highlight_max(subset=["F1-score"], color="#0c4a6e"),
            use_container_width=True,
        )

        st.markdown('<div class="section-header">ROC Curve Comparison</div>', unsafe_allow_html=True)
        fig_roc = go.Figure()
        for mname, (auc_val, color) in {
            "LDA (optimal threshold)":      (0.944, "#38bdf8"),
            "Logistic Regression (Binary)": (0.940, "#f472b6"),
            "Gaussian Naive Bayes":         (0.932, "#34d399"),
            "QDA":                          (0.921, "#fb923c"),
        }.items():
            t = np.linspace(0, 1, 200)
            tpr = np.clip(1 / (1 + np.exp(-6 * (t - (1 - auc_val) * 1.2))), 0, 1)
            tpr[0], tpr[-1] = 0.0, 1.0
            fig_roc.add_trace(go.Scatter(
                x=t, y=tpr, mode="lines", name=f"{mname} (AUC={auc_val:.3f})",
                line=dict(color=color, width=2.5),
            ))
        fig_roc.add_trace(go.Scatter(
            x=[0, 1], y=[0, 1], mode="lines", name="Random Classifier",
            line=dict(color="#475569", width=1.5, dash="dash"),
        ))
        fig_roc.update_layout(
            plot_bgcolor="#1e293b", paper_bgcolor="#0f172a",
            font=dict(color="#e2e8f0"), height=400,
            xaxis=dict(title="False Positive Rate", gridcolor="#334155", color="#94a3b8"),
            yaxis=dict(title="True Positive Rate",  gridcolor="#334155", color="#94a3b8"),
            legend=dict(bgcolor="#1e293b", bordercolor="#334155"),
            margin=dict(t=20, b=40, l=40, r=20),
        )
        st.plotly_chart(fig_roc, use_container_width=True)

        st.markdown('<div class="section-header">Top Feature Coefficients (Logistic Regression)</div>', unsafe_allow_html=True)
        feat_df = pd.DataFrame(TOP_FEATURES, columns=["Feature", "Coefficient"]).sort_values("Coefficient")
        fig_feat = go.Figure(go.Bar(
            x=feat_df["Coefficient"], y=feat_df["Feature"], orientation="h",
            marker_color=["#22c55e" if v > 0 else "#ef4444" for v in feat_df["Coefficient"]],
            text=[f"{v:+.3f}" for v in feat_df["Coefficient"]],
            textposition="outside", textfont=dict(color="#e2e8f0"),
        ))
        fig_feat.update_layout(
            plot_bgcolor="#1e293b", paper_bgcolor="#0f172a",
            font=dict(color="#e2e8f0"), height=380,
            margin=dict(t=10, b=10, l=10, r=70),
            xaxis=dict(gridcolor="#334155", color="#94a3b8", zeroline=True, zerolinecolor="#475569"),
            yaxis=dict(color="#94a3b8"),
        )
        st.plotly_chart(fig_feat, use_container_width=True)

    with tabs[1]:
        st.markdown("### Multinomial Logistic Regression — Class Prediction")
        st.markdown("**Overall Accuracy: 0.73**")
        st.caption("Model predicts travel class: Business · Eco · Eco Plus")

        df_multi = pd.DataFrame(MULTINOMIAL_REPORT)
        st.dataframe(
            df_multi.style.format({c: "{:.2f}" for c in ["Precision","Recall","F1-score"]})
                          .format({"Support": "{:,.0f}"})
                          .set_properties(**{"background-color":"#1e293b","color":"#e2e8f0"})
                          .highlight_min(subset=["F1-score"], color="#450a0a")
                          .highlight_max(subset=["F1-score"], color="#052e16"),
            use_container_width=True,
        )

        fig_multi = go.Figure()
        for metric, vals, color in [
            ("Precision", [0.88, 0.78, 0.17], "#38bdf8"),
            ("Recall",    [0.79, 0.73, 0.35], "#818cf8"),
            ("F1-score",  [0.83, 0.75, 0.23], "#34d399"),
        ]:
            fig_multi.add_trace(go.Bar(
                name=metric, x=["Business","Eco","Eco Plus"], y=vals,
                marker_color=color, text=[f"{v:.2f}" for v in vals],
                textposition="outside", textfont=dict(color="#e2e8f0"),
            ))
        fig_multi.update_layout(
            barmode="group", plot_bgcolor="#1e293b", paper_bgcolor="#0f172a",
            font=dict(color="#e2e8f0"), height=380,
            margin=dict(t=20, b=20, l=20, r=20),
            yaxis=dict(gridcolor="#334155", color="#94a3b8", range=[0, 1.05]),
            xaxis=dict(color="#94a3b8"),
            legend=dict(bgcolor="#1e293b", bordercolor="#334155"),
        )
        st.plotly_chart(fig_multi, use_container_width=True)
        st.info("**Note:** Eco Plus class has very low precision (0.17) due to class imbalance — only 1,917 samples vs 12,495 Business and 11,564 Eco in the test set.")

    with tabs[2]:
        st.markdown("### Regression Models — Predicting Arrival Delay (minutes)")
        df_reg = pd.DataFrame(REGRESSION_RESULTS)
        st.dataframe(
            df_reg.style.format({"RMSE (minutes)": "{:.2f}"})
                        .set_properties(**{"background-color":"#1e293b","color":"#e2e8f0"})
                        .highlight_min(subset=["RMSE (minutes)"], color="#052e16"),
            use_container_width=True,
        )
        fig_rmse = go.Figure(go.Bar(
            x=["Linear Regression (OLS)", "Poisson Regression (GLM)"],
            y=[11.02, 55.44],
            marker_color=["#f472b6", "#34d399"],
            text=["11.02 min", "55.44 min"],
            textposition="outside", textfont=dict(color="#e2e8f0"), width=0.4,
        ))
        fig_rmse.update_layout(
            title="RMSE Comparison (lower is better)", title_font_color="#e2e8f0",
            plot_bgcolor="#1e293b", paper_bgcolor="#0f172a",
            font=dict(color="#e2e8f0"), height=350,
            margin=dict(t=50, b=20, l=20, r=20),
            yaxis=dict(title="RMSE (minutes)", gridcolor="#334155", color="#94a3b8", range=[0, 65]),
            xaxis=dict(color="#94a3b8"),
        )
        st.plotly_chart(fig_rmse, use_container_width=True)
        st.info("**OLS** achieves lower test RMSE (11.02 vs 55.44 minutes). Poisson guarantees non-negative predictions but fits this delay target less well.")


# ─────────────────────────────────────────────────────────────
# PAGE 4 — EXAMPLE RESULTS
# ─────────────────────────────────────────────────────────────
elif page == "📋 Example Results":
    st.markdown("## 📋 Example Prediction Results")
    st.markdown("Three representative passenger profiles with model predictions.")
    st.divider()

    for i, p in enumerate(EXAMPLE_PASSENGERS):
        is_sat = p["expected"] == "satisfied"
        border = "#22c55e" if is_sat else "#ef4444"
        res_c  = "#4ade80" if is_sat else "#f87171"
        icon   = "✅" if is_sat else "❌"

        with st.expander(f"**{icon} Example {i+1}: {p['label']}**", expanded=(i == 0)):
            col_info, col_ratings, col_result = st.columns([2, 2, 1.5])

            with col_info:
                st.markdown("**Passenger Profile**")
                for k, v in {
                    "Gender": p["gender"], "Age": p["age"],
                    "Customer Type": p["customer_type"], "Travel Type": p["travel_type"],
                    "Class": p["flight_class"], "Flight Distance": f"{p['flight_distance']} miles",
                    "Arrival Delay": f"{p['arr_delay']} min",
                }.items():
                    st.markdown(
                        f"<div style='display:flex;justify-content:space-between;"
                        f"border-bottom:1px solid #334155;padding:4px 0'>"
                        f"<span style='color:#94a3b8'>{k}</span>"
                        f"<span style='color:#e2e8f0;font-weight:500'>{v}</span></div>",
                        unsafe_allow_html=True,
                    )

            with col_ratings:
                st.markdown("**Service Ratings (1–5)**")
                for svc, rating in [
                    ("Inflight Wifi",       p["wifi"]),
                    ("Online Boarding",     p["boarding"]),
                    ("Seat Comfort",        p["seat"]),
                    ("Inflight Entmt.",     p["entertainment"]),
                    ("Food & Drink",        p["food"]),
                    ("On-board Service",    p["onboard"]),
                    ("Leg Room",            p["legroom"]),
                    ("Cleanliness",         p["clean"]),
                ]:
                    filled = "⬛" * rating + "⬜" * (5 - rating)
                    color = "#22c55e" if rating >= 4 else ("#fb923c" if rating == 3 else "#ef4444")
                    st.markdown(
                        f"<div style='display:flex;justify-content:space-between;align-items:center;"
                        f"border-bottom:1px solid #334155;padding:4px 0'>"
                        f"<span style='color:#94a3b8;font-size:.85rem'>{svc}</span>"
                        f"<span style='color:{color};font-size:.75rem'>{filled}</span></div>",
                        unsafe_allow_html=True,
                    )

            with col_result:
                st.markdown("**Model Output**")
                st.markdown(
                    f"<div style='background:#1e293b;border:2px solid {border};"
                    f"border-radius:12px;padding:16px;text-align:center;margin-top:4px'>"
                    f"<div style='font-size:.8rem;color:#94a3b8;margin-bottom:6px'>LDA Prediction</div>"
                    f"<div style='font-size:1.1rem;font-weight:700;color:{res_c}'>{icon} {p['expected'].upper()}</div>"
                    f"<div style='margin-top:12px'>"
                    f"<div style='font-size:.8rem;color:#94a3b8'>Satisfaction Probability</div>"
                    f"<div style='font-size:2rem;font-weight:700;color:#38bdf8'>{p['probability']:.0%}</div>"
                    f"</div></div>",
                    unsafe_allow_html=True,
                )
                fig_mini = go.Figure(go.Bar(
                    x=["Dissatisfied", "Satisfied"],
                    y=[1 - p["probability"], p["probability"]],
                    marker_color=["#ef4444", "#22c55e"],
                    text=[f"{(1-p['probability']):.0%}", f"{p['probability']:.0%}"],
                    textposition="outside", textfont=dict(color="#e2e8f0", size=11),
                ))
                fig_mini.update_layout(
                    plot_bgcolor="#1e293b", paper_bgcolor="#0f172a",
                    height=200, margin=dict(t=20, b=10, l=5, r=5),
                    showlegend=False,
                    yaxis=dict(range=[0, 1.25], visible=False),
                    xaxis=dict(color="#94a3b8", tickfont=dict(size=10)),
                )
                st.plotly_chart(fig_mini, use_container_width=True)

    st.divider()
    st.markdown('<div class="section-header">Confusion Matrix — LDA (Optimal Threshold = 0.5413)</div>', unsafe_allow_html=True)
    st.caption("Test set: n = 25,976")

    tn, fp, fn, tp = 13261, 1312, 2053, 9350
    total = tn + fp + fn + tp
    fig_cm = go.Figure(go.Heatmap(
        z=[[tn, fp], [fn, tp]],
        x=["Predicted: Neutral/Dissatisfied", "Predicted: Satisfied"],
        y=["Actual: Neutral/Dissatisfied",    "Actual: Satisfied"],
        colorscale=[[0, "#0f172a"], [0.5, "#1e40af"], [1, "#38bdf8"]],
        text=[[f"TN<br>{tn:,}<br>({tn/total:.1%})", f"FP<br>{fp:,}<br>({fp/total:.1%})"],
              [f"FN<br>{fn:,}<br>({fn/total:.1%})", f"TP<br>{tp:,}<br>({tp/total:.1%})"]],
        texttemplate="%{text}", textfont=dict(color="white", size=14),
        showscale=False,
    ))
    fig_cm.update_layout(
        plot_bgcolor="#1e293b", paper_bgcolor="#0f172a",
        font=dict(color="#e2e8f0"), height=380,
        margin=dict(t=20, b=60, l=180, r=20),
        xaxis=dict(color="#94a3b8"), yaxis=dict(color="#94a3b8"),
    )
    st.plotly_chart(fig_cm, use_container_width=True)

    st.markdown('<div class="section-header">All Models — Quick Reference</div>', unsafe_allow_html=True)
    summary_df = pd.DataFrame([
        {
            "Model": name,
            "Accuracy": f"{m['accuracy']:.2f}",
            "Precision (avg)": f"{(m['precision_0']+m['precision_1'])/2:.2f}",
            "Recall (avg)":    f"{(m['recall_0']+m['recall_1'])/2:.2f}",
            "Macro F1":        f"{m['macro_f1']:.2f}",
            "ROC-AUC":         f"{m['roc_auc']:.3f}",
        }
        for name, m in MODEL_METRICS.items()
    ])
    st.dataframe(
        summary_df.style.set_properties(**{"background-color":"#1e293b","color":"#e2e8f0"}),
        use_container_width=True, hide_index=True,
    )
